name: asb-baalchip
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base=4.0.5
  - bioconductor-baalchip=1.24.0
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bowtie2=2.2.5
  - samtools=1.9
  - picard=2.25.1
